FROM mysql:8
COPY /docker/cd/db/init_users.sh /docker-entrypoint-initdb.d/init_users.sh
COPY /docker/cd/db/init_table.sh /docker-entrypoint-initdb.d/init_table.sh
RUN chmod u+x /docker-entrypoint-initdb.d/init_users.sh && \
chmod u+x /docker-entrypoint-initdb.d/init_table.sh