#!/bin/bash

set -e

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT SELECT, INSERT, UPDATE ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
GRANT SELECT, INSERT, UPDATE ON ${MYSQL_AUTH_DATABASE}.* TO '${MYSQL_USER}'@'%';
EOSQL
